pub mod appbar;
pub mod backdrop;
pub mod cards;
pub mod context;
pub mod events;
pub mod flyout;
pub mod fullscreen;
pub mod renderer;
pub mod startup;
pub mod state;
pub mod theme;
pub mod tray;

pub use appbar::AppBarManager;
pub use backdrop::BackdropManager;
pub use events::wnd_proc;
pub use flyout::{apply_window_styling, calculate_window_dimensions, create_flyout_window, hide_flyout, show_flyout, toggle_visibility};
pub use fullscreen::FullscreenDetector;
pub use renderer::UIRenderer;
pub use startup::StartupManager;
pub use state::{get_app_state, init_app_state, AppState, BASE_HEIGHT, BASE_WIDTH};
pub use theme::ThemePalette;
pub use tray::SystemTray;
